### ISSUE TITLE
Header 组件 fixed 状态下 fixed-margin 的距离存在问题

### ISSUE THREAD

**Issue by Slouchwind** [wux-ui/wux-ui#10]
## 🍡 附加图片
![image](https://user-images.githubusercontent.com/81954768/187641930-66740034-eb7e-4a8f-acfc-1a0bf1bf31be.png) 
## 🥂 可能的解决方案
为在 `wux-header-fixed` 状态下的 Header 组件写一个 `::after` 以确保距离正确

**Comment by wuxian425** [comment]
阅，已列入排程。

Slouchwind ***@***.***> 于 2022年8月31日周三 17:06写道：

**Comment by wuxian425** [comment]
Try to fixed on c8ed7fb7631817722200a0a75fc8a32ace1da4a1 and 3145eaab21205e4d1b736f344a8e73e5663b33f4
