### ISSUE TITLE
README里链接错了

### ISSUE THREAD

**Issue by Gtd232** [wux-ui/wux-ui#15]
![image](https://user-images.githubusercontent.com/79702405/204128085-dc54cf2a-c03b-4e9f-982e-89432d0819b9.png)  
这会导致转向https://github.com/debug.wux-ui.tk  
![image](https://user-images.githubusercontent.com/79702405/204128132-09f7eda3-e113-49a4-abba-9e4f24060ead.png)
应将`<a href="https:/debug.wux-ui.tk/">Debug</a> / `改为`<a href="https://debug.wux-ui.tk/">Debug</a> / `

**Comment by wuxian425** [comment]
Fixed on f2da808 :smiley:
