### ISSUE TITLE
苹果端Upload组件无文字

### ISSUE THREAD

**Issue by Slouchwind** [wux-ui/wux-ui#6]
用电脑模拟一下，大概这样  
![image](https://user-images.githubusercontent.com/81954768/183966671-a2843629-3acc-482c-a5e3-4dc7df213f16.png)  
要不咱丢了苹果端吧🍭

**Comment by wuxian425** [comment]
自己填文字

**Comment by wuxian425** [comment]
作为兼容，使用按钮重新写了Upload组件样式
