### ISSUE TITLE
Dialog弹窗位置有点靠下

### ISSUE THREAD

**Issue by Gtd232** [wux-ui/wux-ui#9]
![图片](https://user-images.githubusercontent.com/79702405/187161085-5430c8aa-cae5-4ecc-bc2d-302aedb9e7e0.png)  
能不能在中间，或者靠上一点  
FireFox Nightly106.0a1 64位
系统是Kali（基于Debian）

**Comment by Gtd232** [comment]
![图片](https://user-images.githubusercontent.com/79702405/187161670-1e0c133f-c684-472f-8645-df5c68aa6f22.png)

**Comment by wuxian425** [comment]
已确认

**Comment by wuxian425** [comment]
Fixed
